### ISSUE TITLE
cn-latest 分支：升级 vite-plugin-vue-layouts 后，文章列表重复

### ISSUE THREAD

**Issue by raylanw** [Zhengqbbb/qbb.sh#8]
## 背景
我拉取 cn-latest 分支后，尝试使用 github page 进行部署，我参考网上的教程给项目加入了 deploy workflow，部署成功后结果发现访问时存在问题，后来我重新拉取了 cn-latest 分支在本地进行打包，发现打包后会生成一个没有文件名的 html 文件，它的内容和 index.html 一样：
![image](https://user-images.githubusercontent.com/122736456/221388956-6910f3ac-a59e-4ee2-97df-4a363e76a493.png)
这导致 github page 无法正常工作。

## 问题
随后我在网上搜寻解决方案，最后发现 vite-plugin-vue-layouts 这个 repo 中的一个 [PR](https://github.com/JohnCampionJr/vite-plugin-vue-layouts/pull/97)，产生额外文件的问题已经被解决，因此我将 vite-plugin-vue-layouts 升级到 0.8.0 版本。但是，当我重新启动项目后，Blog 这个页面出现了重复的文章列表：
![image](https://user-images.githubusercontent.com/122736456/221389262-d4720b36-e1cf-4beb-9cd6-d440ba5d2fb5.png)

## 求助
首先非常感谢作者能够开源一个这么棒的博客站点模板，让我轻松地建立了自己的网站，因为本人对前端知识掌握程度还没有那么深，也尝试了各种方法，最终还是没能解决，所以来这里发 issue 求助。

**Comment by Zhengqbbb** [comment]
你好感谢关注和提出这个问题：
1. fixed : https://github.com/Zhengqbbb/qbb.sh/commit/1b0793ecae553a1d71f03c3280ee33e6b919ab43

- 不过还是有个小建议，如果前端知识掌握程度还没有那么深，建议还是使用开箱即用的 静态站点生成工具较好 例如 Vitepress
- 但是你个人比较感兴趣或是喜欢折腾的话，可以慢慢理解慢慢搭建

<img width="759" alt="image" src="https://user-images.githubusercontent.com/40693636/221456538-e4192b60-4daa-467d-b96c-a9f237c95e68.png">

再次感谢你的支持 😁
